version: '3.1'

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    init: true
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1