version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3654:80
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1