name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2 
      -
        name: copy docker-compose to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP_ADDRESS }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "prod_configs/db/docker-compose.yml"
          target: "db" # website folder
      -
        name: deploy the container and run init scripts where necessary
        uses: appleboy/ssh-action@master
        env:
          GIT_TOKEN: ${{ secrets.SHIP_IT }}
        with:
          host: ${{ secrets.SSH_IP_ADDRESS }}
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: git_token
          script: |
            echo "$GIT_TOKEN" | docker login ghcr.io -u drakumus --password-stdin
            docker pull ghcr.io/drakumus/db-image:latest
            cd db/prod_configs/db/
            docker-compose up -d --remove-orphans